version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./:/code
    env_file:
      - .env/vars
      - .env/.secrets
    stdin_open: true
    tty: true 

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env/.secrets
